### ISSUE TITLE
Minor typo in project.clj

### ISSUE THREAD

**Issue by alexpw** [vlacs/helmsman#4]
-[compojure "1.1.6" :exclodes [ring/ring-core]]
+[compojure "1.1.6" :exclusions [ring/ring-core]]

**Comment by jrdoane** [comment]
This has been updated in github so if you use something like lein voom, you can see the change right away. It will make it out on the next clojars deployment.

**Comment by jrdoane** [comment]
Pushed into clojars and version was bumped to 0.2.5.
https://github.com/vlacs/helmsman/commit/59aa2c39590cb53fb645c8dcd81ecc25fe5733e1
